channels:
  - defaults
  - conda-forge
  - opensourceeconomics

dependencies:
  - python=3.7
  - ipython
  - nbsphinx
  - sphinx
  - jupyter_client
  - numpy
  - pandas
  - scipy
  - seaborn
  - pytest
  - numba
  - chaospy
  - numdifftools
  - respy

  - pip:
    - sphinxcontrib-bibtex<2.0.0
    - pyabc
